using StudentRegistration.EntityFrameworkCore;
using Xunit;

namespace StudentRegistration.EntityFrameworkCore;

public class StudentRegistrationEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<StudentRegistrationEntityFrameworkCoreFixture>
{

}
